# Generated by Django 5.0 on 2024-04-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
