# Generated by Django 5.0 on 2024-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='YourDefaultValue', max_length=100),
        ),
    ]
