# Generated by Django 5.0 on 2024-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_student_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
